<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Advanced PHP - Cookies </title>
    <link rel="icon" href="./../favicon.ico">
</head>
<style>
    .img-box {
        display: inline-block;
        text-align: center;
        margin: 0 15px;
    }
</style>

<body>
    <?php
    #Setting a Cookie with setcookie() before any output generated by the script.
    # setcookie(name, value, expire, path, domain, secure)
    # name:	The name of the cookie.
    # value: The value of the cookie. Do not store sensitive information since this value is stored on the user's computer.
    # expires: The expiry date in UNIX timestamp format. After this time cookie will become inaccessible. The default value is 0.
    # path: Specify the path on the server for which the cookie will be available. If set to /, the cookie will be available within the entire domain.
    # domain: Specify the domain for which the cookie is available to e.g www.example.com.
    # secure: This field, if present, indicates that the cookie should be sent only if a secure HTTPS connection exists.
    setcookie("username", "Mohed", time() + 30 * 24 * 60 * 60);

    # Accessing Cookies Values using $_COOKIE: 
    echo $_COOKIE["username"];
    echo "<br>";

    ?>

    <?php

    if (isset($_COOKIE["username"])) {
        echo "Hi " . $_COOKIE["username"];
        echo "<br>";
    } else {
        echo "Welcome Guest!";
        echo "<br>";
    }

    ?>

    <?php

    print_r($_COOKIE);
    echo "<hr>";
    ?>

    <?php
    #Removing Cookies: By calling the same setcookie() function with the cookie name
    setcookie("username", "", time() - 3600)
    ?>

</body>

</html>